(*Generated by Lem from elab.lem.*)
open HolKernel Parse boolLib bossLib;
open pervasives_extraTheory libTheory astTheory elabTheory;

val _ = numLib.prefer_num();



val _ = new_theory "elabAuxiliary"


(****************************************************)
(*                                                  *)
(* Termination Proofs                               *)
(*                                                  *)
(****************************************************)

(* val gst = Defn.tgoal_no_defn (elab_p_def, elab_p_ind) *)
val (elab_p_rw, elab_p_ind_rw) =
  Defn.tprove_no_defn ((elab_p_def, elab_p_ind),
    (* the termination proof *)
  )
val elab_p_rw = save_thm ("elab_p_rw", elab_p_rw);
val elab_p_ind_rw = save_thm ("elab_p_ind_rw", elab_p_ind_rw);


(* val gst = Defn.tgoal_no_defn (elab_e_def, elab_e_ind) *)
val (elab_e_rw, elab_e_ind_rw) =
  Defn.tprove_no_defn ((elab_e_def, elab_e_ind),
    (* the termination proof *)
  )
val elab_e_rw = save_thm ("elab_e_rw", elab_e_rw);
val elab_e_ind_rw = save_thm ("elab_e_ind_rw", elab_e_ind_rw);


(* val gst = Defn.tgoal_no_defn (elab_t_def, elab_t_ind) *)
val (elab_t_rw, elab_t_ind_rw) =
  Defn.tprove_no_defn ((elab_t_def, elab_t_ind),
    (* the termination proof *)
  )
val elab_t_rw = save_thm ("elab_t_rw", elab_t_rw);
val elab_t_ind_rw = save_thm ("elab_t_ind_rw", elab_t_ind_rw);


(* val gst = Defn.tgoal_no_defn (elab_decs_def, elab_decs_ind) *)
val (elab_decs_rw, elab_decs_ind_rw) =
  Defn.tprove_no_defn ((elab_decs_def, elab_decs_ind),
    (* the termination proof *)
  )
val elab_decs_rw = save_thm ("elab_decs_rw", elab_decs_rw);
val elab_decs_ind_rw = save_thm ("elab_decs_ind_rw", elab_decs_ind_rw);


(* val gst = Defn.tgoal_no_defn (elab_spec_def, elab_spec_ind) *)
val (elab_spec_rw, elab_spec_ind_rw) =
  Defn.tprove_no_defn ((elab_spec_def, elab_spec_ind),
    (* the termination proof *)
  )
val elab_spec_rw = save_thm ("elab_spec_rw", elab_spec_rw);
val elab_spec_ind_rw = save_thm ("elab_spec_ind_rw", elab_spec_ind_rw);


(* val gst = Defn.tgoal_no_defn (elab_prog_def, elab_prog_ind) *)
val (elab_prog_rw, elab_prog_ind_rw) =
  Defn.tprove_no_defn ((elab_prog_def, elab_prog_ind),
    (* the termination proof *)
  )
val elab_prog_rw = save_thm ("elab_prog_rw", elab_prog_rw);
val elab_prog_ind_rw = save_thm ("elab_prog_ind_rw", elab_prog_ind_rw);




val _ = export_theory()

