#!/bin/sh
# Usage: gen_candle_boot.sh SOURCE... PUBLIC
# Prints candle_boot.cml: the parser SOURCE files and PUBLIC wrapped in
# local ... in ... end, so that only PUBLIC's structure is visible,
# followed by candle_glue.cml. Run from this directory.
set -e
printf '(*\n'
printf '  Candle REPL startup, generated by gen_candle_boot.sh from the parser\n'
printf '  sources and candle_glue.cml.\n'
printf '*)\n'
printf 'local\n'
while [ $# -gt 1 ]; do
  printf '\n'
  cat "$1"
  shift
done
printf '\nin\n\n'
cat "$1"
printf '\nend;\n\n'
cat candle_glue.cml
