#!/usr/bin/env groovy

node("Builder") {

    def build_dir = pwd()  // Record the root build dir
    def build_image        // The Docker image to run in

    stage('Cleaning') {
        sh 'ls -A1 | xargs rm -rf'
    }

    stage('Get CakeML source') {
        checkout([$class: 'GitSCM',
            branches: scm.branches,
            doGenerateSubmoduleConfigurations: false,
            shallow: true,
            extensions: [[$class: 'RelativeTargetDirectory',
                relativeTargetDir: 'cakeml']],
            submoduleCfg: [],
            userRemoteConfigs: scm.userRemoteConfigs])
    }

    stage("Build Docker image") {
        dir('cakeml/developers') {
            build_image = docker.build("cake_ml:latest")
        }
    }

    stage('HOL') {
        checkout([$class: 'GitSCM',
            branches: [[name: '*/master']],
            doGenerateSubmoduleConfigurations: false,
            shallow: true,
            extensions: [[$class: 'RelativeTargetDirectory',
                relativeTargetDir: 'HOL']],
            submoduleCfg: [],
            userRemoteConfigs: [[url: 'https://github.com/HOL-Theorem-Prover/HOL.git']]])

        build_image.inside('-e HOME=/tmp') {
            sh '''echo 'val OS = "linux";' > HOL/tools-poly/jenkins-configure.sml'''
            sh '''echo 'val poly = "/usr/bin/poly";' >> HOL/tools-poly/jenkins-configure.sml'''
            sh '''echo 'val polyc = "/usr/bin/polyc";' >> HOL/tools-poly/jenkins-configure.sml'''
            sh '''echo 'val polymllibdir = "/usr/lib/x86_64-linux-gnu/";' >> HOL/tools-poly/jenkins-configure.sml'''
            sh "echo 'val holdir = \"${build_dir}/HOL\";' >> HOL/tools-poly/jenkins-configure.sml"
            sh '''echo 'val DOT_PATH = "/usr/bin/dot";' >> HOL/tools-poly/jenkins-configure.sml'''
            sh '''echo 'val MLTON = SOME "/usr/bin/mlton";' >> HOL/tools-poly/jenkins-configure.sml'''
            sh '''echo 'use (OS.Path.concat(OS.Path.concat(holdir,"tools-poly"),"configure.sml"))' >> HOL/tools-poly/jenkins-configure.sml'''
            sh 'cd HOL && poly --script tools/jenkins-configure.sml'
            sh 'cd HOL && bin/build --nograph'
        }
    }

    stage('CakeML') {
        withEnv(["PATH+EXTRA=${build_dir}/HOL/bin",  // The PATH+SOMETHING syntax preserves the existing PATH
                 'LC_ALL=en_AU.UTF-8',
                 'LANG=en_AU.UTF-8']) {
            build_image.inside('-e HOME=/tmp') {
                sh 'cd cakeml && bash ./developers/build-email.sh'
            }
        }
    }
}
