(*Generated by Lem from initialProgram.lem.*)
open HolKernel Parse boolLib bossLib;
open lem_pervasivesTheory astTheory semanticPrimitivesTheory;

val _ = numLib.prefer_num();



val _ = new_theory "initialProgram"

(*open import Pervasives*)
(*open import Ast*)
(*open import SemanticPrimitives*)

(*val mk_binop : string -> op -> dec*)
val _ = Define `
 (mk_binop name prim =  
(Dlet (Pvar name) (Fun "x" (Fun "y" (App prim [Var (Short "x"); Var (Short "y")])))))`;


(*val mk_unop : string -> op -> dec*)
val _ = Define `
 (mk_unop name prim =  
(Dlet (Pvar name) (Fun "x" (App prim [Var (Short "x")]))))`;


(*val prim_types_program : prog*)
val _ = Define `
 (prim_types_program =  
([Tdec (Dexn "Bind" []);
   Tdec (Dexn "Div" []);
   Tdec (Dexn "Eq" []);
   Tdec (Dexn "Subscript" []);
   Tdec (Dtype [(["'a"], "list", [("nil", []); ("::", [Tvar "'a"; Tapp [Tvar "'a"] (TC_name (Short "list"))]) ])]);
   Tdec (Dtype [(["'a"], "option", [("NONE", []);("SOME", [Tvar "'a"]) ])]) ]))`;


(*val basis_program : prog*)
val _ = Define `
 (basis_program =  
([Tdec (mk_binop "+" (Opn Plus));
   Tdec (mk_binop "-" (Opn Minus));
   Tdec (mk_binop "*" (Opn Times));
   Tdec (mk_binop "div" (Opn Divide));
   Tdec (mk_binop "mod" (Opn Modulo));
   Tdec (mk_binop "<" (Opb Lt));
   Tdec (mk_binop ">" (Opb Gt));
   Tdec (mk_binop "<=" (Opb Leq));
   Tdec (mk_binop ">=" (Opb Geq));
   Tdec (mk_binop "=" Equality);
   Tdec (mk_binop ":=" Opassign);
   Tdec (Dlet (Pvar "~") (Fun "x" (App (Opn Minus) [Lit (IntLit(( 0 : int))); Var(Short"x")])));
   Tdec (mk_unop "!" Opderef);
   Tdec (mk_unop "ref" Opref);
   Tmod "Word8" NONE [];
   Tmod "Word8Array" NONE 
     [mk_binop "array" Aalloc;
      mk_binop "sub" Asub;
      mk_unop "length" Alength;
      Dlet (Pvar "update") (Fun "x" (Fun "y" (Fun "z" (App Aupdate [Var (Short "x"); Var (Short "y"); Var (Short "z")])))) ] ]))`;


(* The initial mapping of type names to primitive type constructors, for the elaborator *)
val _ = Define `
 (init_type_bindings =  
([("int", TC_int);
   ("bool", TC_bool);
   ("ref", TC_ref);
   ("exn", TC_exn);
   ("unit", TC_unit);
   ("list", TC_name (Short "list"));
   ("option", TC_name (Short "option"))]))`;


val _ = Hol_datatype `
 sem_environment = <| sem_envM : envM;
                          sem_envC : envC;
                          sem_envE : envE;
                          sem_s : v store;
                          sem_tids : tid_or_exn set;
                          sem_mdecls : modN set |>`;


val _ = export_theory()

