(*Generated by Lem from tokens.lem.*)
open HolKernel Parse boolLib bossLib;
open lem_pervasives_extraTheory;

val _ = numLib.prefer_num();



val _ = new_theory "tokens"

(*open import Pervasives_extra*)
(* Tokens for Standard ML.  NB, not all of them are used in CakeML *)
val _ = Hol_datatype `
 token =
  WhitespaceT of num | NewlineT | LexErrorT
| HashT | LparT | RparT | StarT | CommaT | ArrowT | DotsT | ColonT | SealT
| SemicolonT | EqualsT | DarrowT | LbrackT | RbrackT | UnderbarT | LbraceT
| BarT | RbraceT | AndT | AndalsoT | AsT | CaseT | DatatypeT
| ElseT | EndT | EqtypeT | ExceptionT | FnT | FunT | HandleT | IfT
| InT | IncludeT | LetT | LocalT | OfT | OpT
| OpenT | OrelseT | RaiseT | RecT | SharingT | SigT | SignatureT | StructT
| StructureT | ThenT | TypeT | ValT | WhereT | WhileT | WithT | WithtypeT
| IntT of int
| HexintT of string
| RealT of string
| StringT of string
| CharT of string
| TyvarT of string
| AlphaT of string
| SymbolT of string
| LongidT of string => string`;

val _ = export_theory()

